name: Build and Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '20'

     - name: Install Dependencies-Service
       run: npm install
       working-directory: Moviein/servidor

     - name: Install Dependencies-Client
       run: npm install
       working-directory: Moviein/cliente/moviein

     - name: Build Project
       run: |
        npm run build
       working-directory: Moviein/cliente/moviein

     - name: clear node_modules
       run: |
        rm -rf node_modules
       working-directory: Moviein/cliente/moviein
       
     - name: Deploy to Server
       uses: wlixcc/SFTP-Deploy-Action@v1.2.4
       with:
          username: 'bitnami'
          server: '${{ secrets.AWS_INSTANCE_IP }}'
          ssh_private_key: ${{ secrets.AWS_SSH_KEY }}
          local_path: 'Moviein/cliente/moviein'
          remote_path: '/opt/bitnami/apache/htdocs'
          sftpArgs: '-o ConnectTimeout=5'
          exclude: 'node_modules'
          rsyncFlags: '--exclude=node_modules'

     - name: Prepare SSH Key and Start Node.js Server
       run: |
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          ssh-keygen -R ${{ secrets.AWS_INSTANCE_IP }}
          echo "${{ secrets.AWS_SSH_KEY }}" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem bitnami@${{ secrets.AWS_INSTANCE_IP }} "pm2 start ./htdocs/moviein/server.js"
       shell: bash
