name: Build and Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '20'

     - name: Install Dependencies-Service
       run: npm install
       working-directory: Moviein/servidor

     - name: Install Dependencies-Client
       run: npm install
       working-directory: Moviein/cliente/moviein

     - name: Build Project
       run: npm run build
       working-directory: Moviein/cliente/moviein

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS Lightsail
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.AWS_INSTANCE_IP }}
          username: ${{ secrets.AWS_INSTANCE_USER }}
          key: ${{secrets.AWS_SSH_KEY}}
          src: "Moviein/cliente/moviein"
          remote: "opt/bitnami/apache/htdocs"
          
