name: Build and Deploy

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2

     - name: Setup Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '20'

     - name: Install Dependencies-Service
       run: npm install
       working-directory: Moviein/servidor

     - name: Install Dependencies-Client
       run: npm install
       working-directory: Moviein/cliente/moviein

     - name: Build Project
       run: npm run build
       working-directory: Moviein/cliente/moviein
       
  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps: 
          - name: Change SSH key permissions
            run: echo "${{ secrets.AWS_SSH_KEY }}" > ssh_key.pem && chmod 600 ssh_key.pem

          - name: Install rsync
            run: sudo apt-get update && sudo apt-get install -y rsync

          - name: Deploy to AWS Lightsail
            run: |
              rsync -avz --exclude 'node_modules' -e "ssh -o StrictHostKeyChecking=no -i ssh_key.pem" Moviein/cliente/moviein/ ${{ secrets.AWS_INSTANCE_USER }}@${{ secrets.AWS_INSTANCE_IP }}:/opt/bitnami/apache/htdocs
            env:
              SSH_PRIVATE_KEY: $(cat ssh_key.pem)
